### ISSUE TITLE
Please update major tag `v1` to be up to date with the latest minor tag `v1.1`

### ISSUE THREAD

**Issue by jamacku** [fedora-copr/vcs-diff-lint-action#6]
Recently added GitHub Action [Actions-R-Us/actions-tagger](https://github.com/Actions-R-Us/actions-tagger#readme) requires a semantic versioning structure to work correctly (e.g. `v1.0.0`, `v1.1.0`, `v1.2.0`).

**Comment by praiskup** [comment]
So can I just tag with `v1.0.1`, and things will happen automatically?

**Comment by jamacku** [comment]
Yes, `v1.0.1` is sufficient.

**Comment by praiskup** [comment]
I tagged with v1.1.2, and it has no effect.  Any idea?

**Comment by jamacku** [comment]
I'm sorry, I have copied workflow from the repo when I always publish releases. Hence in the workflow is trigger [`on: release`](https://github.com/fedora-copr/vcs-diff-lint-action/blob/main/.github/workflows/publish-release.yml#L6-L7)

You can publish a release with the existing tag `v1.1.2`, and it should start tagging workflow. I'll create a new PR adding an option to run tagging workflow on the tag push event as well.

**Comment by jamacku** [comment]
Ok, so I have tried it on my fork, and running on tag push isn't supported. Output form action:

```
Run Actions-R-Us/actions-tagger@v2
This action should only be used in a release context
If you believe this to be an error, please submit a bug report
https://github.com/Actions-R-Us/actions-tagger/issues
```

I can submit RFE for that. But for now, it runs only on releases.

**Comment by praiskup** [comment]
Ok, let's do releases for now.  Thanks!
